spring:
  application:
    name: cellphones-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://db.supabase.co:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      time-to-live: 3600000 # 1 hour
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
